server {
    server_name  listen.hatnote.com l2w.hatnote.com;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/hatnote.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hatnote.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root  /home/hatnote/listen/static/;
    access_log  /home/hatnote/listen/logs/access.log combined buffer=128k flush=10s;
    error_log  /home/hatnote/listen/logs/error.log;

    expires  1d;
}

server {
    server_name  listen.hatnote.com l2w.hatnote.com;
    listen  80;
    return 301 https://$host$request_uri;
}
